"use strict";
const S=require('./schema');
function slugify(v){return String(v||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').replace(/-+/g,'-');}
function normalizeTrip(input={}){const t=input.trip||{};return {runId:String(input.runId||''),source:String(input.source||'manual'),trip:{date:String(t.date||''),author:String(t.author||'aniket'),destination:String(t.destination||''),duration:String(t.duration||''),rawNotes:String(t.rawNotes||''),routeNotes:String(t.routeNotes||''),costNotes:String(t.costNotes||''),gearNotes:String(t.gearNotes||''),mustInclude:Array.isArray(t.mustInclude)?t.mustInclude.map(String):[]},photos:Array.isArray(input.photos)?input.photos:[],routeImages:Array.isArray(input.routeImages)?input.routeImages:[]};}
function validateGenerated(x){const e=[];const fail=m=>e.push(m);const allowed=(v,a,l)=>{if(!a.includes(v))fail(`${l}: invalid value ${JSON.stringify(v)}`)};if(!x||typeof x!=='object')return ['output must be object'];const f=x.frontmatter||{};if(f.draft!==true)fail('draft must be true');if(typeof f.featured!=='boolean')fail('featured must be boolean');allowed(f.author,S.AUTHORS,'author');allowed(f.categories,S.CATEGORIES,'categories');for(const [k,a] of [['travelType',S.TRAVEL_TYPES],['rideMode',S.RIDE_MODES],['activities',S.ACTIVITIES],['tags',S.TAGS]])for(const v of (Array.isArray(f[k])?f[k]:[]))allowed(v,a,k);if(!Array.isArray(f.tags)||!f.tags.includes('post'))fail('tags must include post');if(f.layout!=='article.njk')fail('layout must be article.njk');if(!String(f.title||'').trim())fail('title required');if(!String(f.description||'').trim())fail('description required');if(!String(x.bodyMarkdown||'').trim())fail('bodyMarkdown required');if(/^---\s*$/m.test(String(x.bodyMarkdown||'')))fail('bodyMarkdown may not contain front matter delimiter');const td=f.tripDetails||{},d=td.difficulty||{};if(d.overall!==undefined&&d.overall!=='')allowed(d.overall,S.DIFFICULTY,'difficulty.overall');for(const k of ['physical','technical'])if(d[k]!==undefined&&d[k]!==''&&(!Number.isInteger(d[k])||d[k]<1||d[k]>5))fail(`difficulty.${k} must be integer 1..5`);const seasonal=td.seasonal||{};for(const v of (Array.isArray(seasonal.bestSeason)?seasonal.bestSeason:[]))allowed(v,S.SEASONS,'seasonal.bestSeason');const paths=[];for(const k of ['featuredImage','thumbnailImage'])if(f[k])paths.push(f[k]);for(const g of [...(f.gallery||[]),...(f.routeGallery||[])])if(g&&g.src)paths.push(g.src);for(const p of paths){if(!String(p).startsWith('/assets/images/'))fail(`invalid image path ${p}`);if(String(p).includes('..'))fail(`unsafe image path ${p}`)}for(const g of (f.gallery||[]))if(!String(g.alt||'').trim())fail('gallery alt required');return e;}
function scalar(v){if(v===null)return 'null';if(typeof v==='boolean'||typeof v==='number')return String(v);const s=String(v);return s===''?'""':JSON.stringify(s)}
function yamlLines(obj,indent=0){const out=[],pad=' '.repeat(indent);for(const k of Object.keys(obj)){const v=obj[k];if(Array.isArray(v)){if(!v.length)out.push(`${pad}${k}: []`);else{out.push(`${pad}${k}:`);for(const item of v){if(item&&typeof item==='object'&&!Array.isArray(item)){out.push(`${pad}  -`);out.push(...yamlLines(item,indent+4))}else out.push(`${pad}  - ${scalar(item)}`)}}}else if(v&&typeof v==='object'){if(!Object.keys(v).length)out.push(`${pad}${k}: {}`);else{out.push(`${pad}${k}:`);out.push(...yamlLines(v,indent+2))}}else out.push(`${pad}${k}: ${scalar(v)}`)}return out}
function serializeYaml(obj){return yamlLines(obj).join('\n')}
function assembleMarkdown(x){const errors=validateGenerated(x);if(errors.length)throw new Error(errors.join('; '));return `---\n${serializeYaml(x.frontmatter)}\n---\n\n${String(x.bodyMarkdown).trim()}\n`}
function postPath(date,title){if(!/^\d{4}-\d{2}-\d{2}/.test(String(date||'')))throw new Error('date must begin YYYY-MM-DD');const slug=slugify(title);if(!slug)throw new Error('title produces empty slug');return `src/blog/${String(date).slice(0,10)}-${slug}.md`}
module.exports={slugify,normalizeTrip,validateGenerated,serializeYaml,assembleMarkdown,postPath};
