# Decap CMS Configuration matching your existing structure
backend:
  name: git-gateway
  branch: render-blog  # Replace with your actual branch name

# Publish mode
publish_mode: simple

# Media folder paths - using your existing structure
media_folder: "src/assets/images"  # Where media will be stored
public_folder: "/assets/images"    # Public path to that media

# Collections
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: true, hint: "Set to true to save as draft" }
      - { 
          label: "Categories", 
          name: "categories", 
          widget: "list",
          allow_add: true
        }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Image Alt Text", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { 
          label: "Gallery", 
          name: "gallery", 
          widget: "list", 
          required: false,
          fields: [
            { label: "Image", name: "src", widget: "image" },
            { label: "Alt Text", name: "alt", widget: "string" },
            { label: "Caption", name: "caption", widget: "string", required: false },
            { label: "Credit", name: "credit", widget: "string", required: false }
          ]
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Layout", name: "layout", widget: "hidden", default: "article.njk" }

  # Pages as separate file collection entries
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/about.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/about/index.html" }
          - { label: "Body", name: "body", widget: "markdown" }
      
      - label: "Contact Page"
        name: "contact"
        file: "src/contact.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/contact/index.html" }
          - { label: "Body", name: "body", widget: "markdown" }
          
      - label: "Privacy Policy"
        name: "privacy"
        file: "src/privacy-policy.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/privacy-policy/index.html" }
          - { label: "Body", name: "body", widget: "markdown" }