# Decap CMS Configuration - Final version
backend:
  name: git-gateway
  branch: main  # Your confirmed branch name

# Publish mode
publish_mode: simple

# Media folder paths - using your existing structure
media_folder: "src/assets/images"  # Where media will be stored
public_folder: "/assets/images"    # Public path to that media

# Collections
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: true, hint: "Set to true to save as draft" }
      - { 
          label: "Categories", 
          name: "categories", 
          widget: "list",
          allow_add: true
        }
      - { label: "Featured Image", name: "featuredImage", widget: "image", hint: "Main image shown at the top of the post (1200-1600px wide)" }
      - { label: "Thumbnail Image", name: "thumbnailImage", widget: "image", required: false, hint: "Optional smaller image for cards (400x267px). If not provided, featured image will be used." }
      - { label: "Image Alt Text", name: "imageAlt", widget: "string" }
      
      # Travel-specific fields
      - label: "Destination"
        name: "destination"
        widget: "string"
        required: false
        hint: "Main location of this travel post (e.g. 'Bali, Indonesia')"

      - label: "Duration"
        name: "duration"
        widget: "string"
        required: false
        hint: "Duration of the trip (e.g. '7 days', '2 weeks')"

      - label: "Travel Type"
        name: "travelType"
        widget: "select"
        required: false
        options:
          - { label: "Adventure", value: "adventure" }
          - { label: "Cultural", value: "cultural" }
          - { label: "Food & Drink", value: "food" }
          - { label: "Beach", value: "beach" }
          - { label: "Mountains", value: "mountains" }
          - { label: "City Break", value: "city" }
          - { label: "Road Trip", value: "road-trip" }
          - { label: "Budget", value: "budget" }
          - { label: "Luxury", value: "luxury" }
        hint: "Type of travel experience"

      - label: "Activities"
        name: "activities"
        widget: "list"
        required: false
        hint: "Activities featured in this post (e.g. hiking, beach, food tour)"

      - label: "Coordinates"
        name: "coordinates"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - { label: "Latitude", name: "latitude", widget: "number", required: false, valueType: "float" }
          - { label: "Longitude", name: "longitude", widget: "number", required: false, valueType: "float" }
      
      # Original content fields
      - { label: "Body", name: "body", widget: "markdown" }
      - { 
          label: "Gallery", 
          name: "gallery", 
          widget: "list", 
          required: false,
          hint: "Gallery images should be around 800x533px for optimal display",
          fields: [
            { label: "Image", name: "src", widget: "image" },
            { label: "Alt Text", name: "alt", widget: "string" },
            { label: "Caption", name: "caption", widget: "string", required: false },
            { label: "Credit", name: "credit", widget: "string", required: false },
            { label: "Location", name: "location", widget: "string", required: false }
          ]
        }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Layout", name: "layout", widget: "hidden", default: "article.njk" }

  # Pages as separate file collection entries
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/about.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/about/index.html" }
          - { label: "Body", name: "body", widget: "code", default_language: "html", allow_language_selection: false }
      
      - label: "Contact Page"
        name: "contact"
        file: "src/contact.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/contact/index.html" }
          - { label: "Body", name: "body", widget: "code", default_language: "html", allow_language_selection: false }
      
      - label: "Privacy Policy"
        name: "privacy"
        file: "src/privacy-policy.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/privacy-policy/index.html" }
          - { label: "Body", name: "body", widget: "code", default_language: "html", allow_language_selection: false }
      
      - label: "Explore Page"
        name: "explore"
        file: "src/explore.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
          - { label: "Permalink", name: "permalink", widget: "hidden", default: "/explore/index.html" }
          - { label: "Body", name: "body", widget: "code", default_language: "html", allow_language_selection: false }