# Decap CMS Configuration - Final version
backend:
  name: git-gateway
  branch: development # Your confirmed branch name

# Publish mode
publish_mode: simple

# Media folder paths - using your existing structure
media_folder: "src/assets/images"  # Where media will be stored
public_folder: "/assets/images"    # Public path to that media

# Collections
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Draft", name: "draft", widget: "boolean", default: true, hint: "Set to true to save as draft" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Aniket", value: "aniket" } #Value should match the slug property in the author JSON file
          - { label: "Gauri", value: "gauri" } #Value should match the slug property in the author JSON file
          - { label: "Yogesh", value: "yogesh" } #Value should match the slug property in the author JSON file
        hint: "Select the author of this post "
      
      # Travel-specific fields
      - label: "Destination"
        name: "destination"
        widget: "string"
        required: false
        hint: "Main location of this travel post (e.g. 'Bali, Indonesia')"

      - label: "Coordinates"
        name: "coordinates"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - { label: "Latitude", name: "latitude", widget: "number", required: false, valueType: "float" }
          - { label: "Longitude", name: "longitude", widget: "number", required: false, valueType: "float" }

      - label: "Duration"
        name: "duration"
        widget: "string"
        required: false
        hint: "Duration of the trip (e.g. '7 days', '2 weeks')"

      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: false
        options:
          - { label: "Adventure", value: "Adventure" }
          - { label: "Photography", value: "Photography" }
          - { label: "Food", value: "Food" }
          - { label: "Culture", value: "Culture" }
          - { label: "Heritage", value: "Heritage" }
          - { label: "Wildlife", value: "Wildlife" }
          - { label: "Wellness", value: "Wellness" }
          - { label: "Off-Road", value: "Off-Road" }
          - { label: "Luxury Travel", value: "Luxury Travel" }
          - { label: "Solo Travel", value: "Solo Travel" }
          - { label: "Family Travel", value: "Family Travel" }
          - { label: "Sustainable Travel", value: "Sustainable Travel" }
          - { label: "Backpacking", value: "Backpacking" }
          - { label: "Seasonal Travel", value: "Seasonal Travel" }
          - { label: "Hidden Gems", value: "Hidden Gems" }
          - { label: "Urban Exploration", value: "Urban Exploration" }
          - { label: "Rural Getaways", value: "Rural Getaways" }
          - { label: "Coastal Journeys", value: "Coastal Journeys" }
          - { label: "Mountain Expeditions", value: "Mountain Expeditions" }
          - { label: "Weekend Escapes", value: "Weekend Escapes" }
          - { label: "Long-Term Travel", value: "Long-Term Travel" }
          - { label: "Budget Travel", value: "Budget Travel" }
      
      - label: "Travel Type"
        name: "travelType"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "Adventure", value: "adventure" }
          - { label: "Solo Bike Ride", value: "Solo Bike Ride" }
          - { label: "Group Bike Ride", value: "Group Bike Ride" }
          - { label: "Cultural", value: "cultural" }
          - { label: "Food & Drink", value: "food" }
          - { label: "Beach", value: "beach" }
          - { label: "Mountains", value: "mountains" }
          - { label: "City Break", value: "city" }
          - { label: "Road Trip", value: "road-trip" }
          - { label: "Budget", value: "budget" }
          - { label: "Luxury", value: "luxury" }
          - { label: "Backpacking", value: "backpacking" }
          - { label: "Ecotourism", value: "ecotourism" }
          - { label: "Volunteer Travel", value: "volunteer-travel" }
          - { label: "Business Travel", value: "business-travel" }
          - { label: "Medical Tourism", value: "medical-tourism" }
          - { label: "Religious Pilgrimage", value: "religious-pilgrimage" }
          - { label: "Dark Tourism", value: "dark-tourism" }
          - { label: "Educational Travel", value: "educational-travel" }
          - { label: "Extreme Tourism", value: "extreme-tourism" }
          - { label: "Family Vacation", value: "family-vacation" }
          - { label: "Glamping", value: "glamping" }
          - { label: "Heritage Tourism", value: "heritage-tourism" }
          - { label: "Solo Travel", value: "solo-travel" }
          - { label: "Slow Travel", value: "slow-travel" }
          - { label: "Wellness Retreat", value: "wellness-retreat" }
          - { label: "Winter Destination", value: "winter-destination" }
          - { label: "Summer Getaway", value: "summer-getaway" }
          - { label: "Monsoon Destination", value: "monsoon-destination" }
          - { label: "Spring Bloom Location", value: "spring-bloom-location" }
        hint: "Type of travel experience"

      - label: "Activities"
        name: "activities"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "Hiking", value: "Hiking" }
          - { label: "Camping", value: "Camping" }
          - { label: "Waterfall Exploration", value: "Waterfall Exploration" }
          - { label: "Photography", value: "Photography" }
          - { label: "Food Tour", value: "Food Tour" }
          - { label: "Bird Watching", value: "Bird Watching" }
          - { label: "Cycling", value: "Cycling" }
          - { label: "Kayaking", value: "Kayaking" }
          - { label: "Paragliding", value: "Paragliding" }
          - { label: "Rock Climbing", value: "Rock Climbing" }
          - { label: "River Rafting", value: "River Rafting" }
          - { label: "Stargazing", value: "Stargazing" }
          - { label: "Meditation Retreat", value: "Meditation Retreat" }
          - { label: "Cooking Class", value: "Cooking Class" }
          - { label: "Local Crafts Workshop", value: "Local Crafts Workshop" }
          - { label: "Temple Visit", value: "Temple Visit" }
          - { label: "Historical Site Tour", value: "Historical Site Tour" }
          - { label: "Museum Exploration", value: "Museum Exploration" }
          - { label: "Wildlife Safari", value: "Wildlife Safari" }
          - { label: "Snorkeling", value: "Snorkeling" }
          - { label: "Scuba Diving", value: "Scuba Diving" }
          - { label: "Motorcycle Touring", value: "Motorcycle Touring" }
          - { label: "Zip-lining", value: "Zip-lining" }
          - { label: "Bungee Jumping", value: "Bungee Jumping" }
          - { label: "Wine Tasting", value: "Wine Tasting" }
          - { label: "Hot Spring Bathing", value: "Hot Spring Bathing" }
          - { label: "Boat Tour", value: "Boat Tour" }
          - { label: "Architectural Tour", value: "Architectural Tour" }
          - { label: "Street Food Sampling", value: "Street Food Sampling" }
          - { label: "Fishing", value: "Fishing" }
          - { label: "Horseback Riding", value: "Horseback Riding" }
          - { label: "Festival Participation", value: "Festival Participation" }
          - { label: "Village Home Stay", value: "Village Home Stay" }
          - { label: "Beach Relaxation", value: "Beach Relaxation" }
          - { label: "Shopping", value: "Shopping" }
          - { label: "Night Market Exploration", value: "Night Market Exploration" }
          - { label: "Trekking", value: "Trekking" }
          - { label: "Mountain Biking", value: "Mountain Biking" }
          - { label: "Yoga Session", value: "Yoga Session" }
          - { label: "Sunset Viewing", value: "Sunset Viewing" }
          - { label: "Farm Visit", value: "Farm Visit" }
          - { label: "Train Journey", value: "Train Journey" }
          - { label: "Hot Air Ballooning", value: "Hot Air Ballooning" }
        hint: "Activities featured in this post"
        
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        default: ["post"]
        options:
          - { label: "Post", value: "post" }
          - { label: "Monsoon", value: "monsoon" }
          - { label: "Western Ghats", value: "western-ghats" }
          - { label: "Tent Camping", value: "tent-camping" }
          - { label: "Wildlife", value: "wildlife" }
          - { label: "Sunrise", value: "sunrise" }
          - { label: "Foggy", value: "foggy" }
          - { label: "Off-Road", value: "off-road" }
          - { label: "Historical", value: "historical" }
          - { label: "Sunset", value: "sunset" }
          - { label: "Rainy Season", value: "rainy-season" }
          - { label: "First Time Experience", value: "first-time-experience" }
          - { label: "Family Friendly", value: "family-friendly" }
          - { label: "Pet Friendly", value: "pet-friendly" }
          - { label: "Instagram Worthy", value: "instagram-worthy" }
          - { label: "Secluded", value: "secluded" }
          - { label: "Crowd-Free", value: "crowd-free" }
          - { label: "Breathtaking Views", value: "breathtaking-views" }
          - { label: "Budget Friendly", value: "budget-friendly" }
          - { label: "Luxury Experience", value: "luxury-experience" }
          - { label: "Weekend Getaway", value: "weekend-getaway" }
          - { label: "Day Trip", value: "day-trip" }
          - { label: "Multi-Day Journey", value: "multi-day-journey" }
          - { label: "Hidden Trail", value: "hidden-trail" }
          - { label: "Local Cuisine", value: "local-cuisine" }
          - { label: "Traditional Architecture", value: "traditional-architecture" }
          - { label: "Colonial Heritage", value: "colonial-heritage" }
          - { label: "Public Transport", value: "public-transport" }
          - { label: "Accessible", value: "accessible" }
          - { label: "Challenging Terrain", value: "challenging-terrain" }
          - { label: "Roadside Stop", value: "roadside-stop" }
          - { label: "Backpacker Hostel", value: "backpacker-hostel" }
          - { label: "Boutique Stay", value: "boutique-stay" }
          - { label: "Farm Stay", value: "farm-stay" }
          - { label: "Homestay", value: "homestay" }
          - { label: "Unexplored", value: "unexplored" }
          - { label: "Under-Rated", value: "under-rated" }
          - { label: "Must Visit", value: "must-visit" }
          - { label: "Seasonal Attraction", value: "seasonal-attraction" }
          - { label: "Clear Weather", value: "clear-weather" }
          - { label: "Rough Terrain", value: "rough-terrain" }
          - { label: "Beginner Friendly", value: "beginner-friendly" }
          - { label: "Advanced Level", value: "advanced-level" }
          - { label: "Guided Tour", value: "guided-tour" }
          - { label: "Self-Guided", value: "self-guided" }
          - { label: "Remote Location", value: "remote-location" }
          - { label: "Urban Center", value: "urban-center" }
          - { label: "Coastal Road", value: "coastal-road" }
          - { label: "Mountain Pass", value: "mountain-pass" }
          - { label: "Hairpin Bends", value: "hairpin-bends" }
          - { label: "Forest Trail", value: "forest-trail" }
          - { label: "Grassland", value: "grassland" }
          - { label: "Plateau", value: "plateau" }
          - { label: "Valley", value: "valley" }
          - { label: "Riverside", value: "riverside" }
          - { label: "Lakeside", value: "lakeside" }
          - { label: "Desert", value: "desert" }
      
      - label: "Featured Image"
        name: "featuredImage"
        widget: "image"
        hint: "Main image shown at the top of the post (1200-1600px wide recommended)"
      
      - label: "Featured Image Alt Text"
        name: "imageAlt"
        widget: "string"
        hint: "Descriptive text for featured image accessibility"
      
      - label: "Featured Image Credit"
        name: "imageCredit"
        widget: "string"
        required: false
        hint: "Credit for the featured image photographer/source"
      
      - label: "Thumbnail Image"
        name: "thumbnailImage"
        widget: "image"
        required: false
        hint: "Optional smaller image for cards (400x267px recommended)"
      
      - label: "Thumbnail Image Alt Text"
        name: "thumbnailAlt"
        widget: "string"
        required: false
        hint: "Descriptive text for thumbnail image accessibility"
      
      - label: "Thumbnail Image Credit"
        name: "thumbnailCredit"
        widget: "string"
        required: false
        hint: "Credit for the thumbnail image photographer/source"
      
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        hint: "Gallery images should be around 800x533px for optimal display"
        fields:
          - { label: "Image", name: "src", widget: "image", hint: "Recommended size: 800x533px" }
          - { label: "Alt Text", name: "alt", widget: "string" }
          - { label: "Caption", name: "caption", widget: "string", required: false }
          - { label: "Credit", name: "credit", widget: "string", required: false }
          - { label: "Location", name: "location", widget: "string", required: false }

      - label: "Route Gallery"
        name: "routeGallery"
        widget: "list"
        required: false
        hint: "Upload screenshots of your travel routes"
        fields:
          - { label: "Route Image", name: "src", widget: "image", hint: "Screenshot of your route map" }
          - { label: "Route Title", name: "title", widget: "string", hint: "Name of this route (e.g. 'Pune to Raigad')" }
          - { label: "Alt Text", name: "alt", widget: "string", hint: "Descriptive text for accessibility" }
          - { label: "Key Locations", name: "locations", widget: "string", required: false, hint: "Comma-separated list of key locations along the route" }
          - { label: "Route Distance", name: "distance", widget: "string", required: false, hint: "Total distance of this route (e.g. '120 km')" }
          - { label: "Route Duration", name: "duration", widget: "string", required: false, hint: "Approximate travel time (e.g. '2.5 hours')" }
          - { label: "Map Source", name: "mapSource", widget: "string", required: false, hint: "Source of the map (e.g. 'Google Maps', 'OpenStreetMap')" }
      
      # Table of Contents settings
      - label: "Table of Contents"
        name: "showTableOfContents"
        widget: "boolean"
        default: true
        hint: "Show a table of contents for this article"
      
      - label: "Minimum TOC Headings"
        name: "tocMinHeadings"
        widget: "number"
        default: 3
        min: 1
        max: 10
        hint: "Minimum number of headings required to show the table of contents"
      
      # Original content fields
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "article.njk" }

  - name: "authors"
    label: "Authors"
    folder: "src/_data/authors"
    create: true
    format: "json"
    extension: "json"
    slug: "{{fields.slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Used for URL, lowercase with hyphens" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Short Bio", name: "shortBio", widget: "string", hint: "A brief one-line description (max 160 chars)", required: false }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Role", name: "role", widget: "string", required: false, hint: "E.g., Founder, Travel Writer, Photographer" }
      - label: "Social Links"
        name: "social"
        widget: "object"
        required: false
        fields:
          - { label: "Instagram", name: "instagram", widget: "string", required: false }
          - { label: "Twitter", name: "twitter", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
          - { label: "Website", name: "website", widget: "string", required: false }